### ISSUE TITLE
Seperation of files and code optimization

### ISSUE THREAD

**Issue by sohan2410** [secrashi/Connect-Intellect#9]
- We have to add .env.example files in both frontend and backend to have clear understanding which variables need to be added
- Add axios functions in utils folder to be used anywhere in the code which emphasize donot repeat code
- Move nodemon to devDependicies
- Modify CORS policy in server

**Comment by sohan2410** [comment]
pr #4

**Comment by arushi2715** [comment]
Is this issue available?
I would like to work on this one.

**Comment by sohan2410** [comment]
@arushi2715 I've already made pr #4 :(
